import Vue from 'vue'
import colors from 'vuetify/lib/util/colors'
import Vuetify, {
    VApp, VAppBar, VAppBarNavIcon,
    VAlert,
    VAutocomplete,
    VAvatar,
    VBadge,
    VBanner,
    VBottomNavigation,
    VBottomSheet,
    VBreadcrumbs, VBreadcrumbsItem,
    VBtn,
    VBtnToggle,
    VCalendar, VCalendarDaily, VCalendarWeekly, VCalendarMonthly,
    VCard, VCardActions, VCardSubtitle, VCardText, VCardTitle,
    VCarousel, VCarouselItem,
    VCheckbox, VSimpleCheckbox,
    VChip,
    VChipGroup,
    VColorPicker, VColorPickerSwatches, VColorPickerCanvas,
    VContent,
    VCombobox,
    VCounter,
    VDataTable, VDataTableHeader, VEditDialog, VTableOverflow, VSimpleTable, VVirtualTable,
    VDataIterator, VDataFooter,
    VDatePicker, VDatePickerTitle, VDatePickerHeader, VDatePickerDateTable, VDatePickerMonthTable, VDatePickerYears,
    VDialog,
    VDivider,
    VExpansionPanels, VExpansionPanel, VExpansionPanelHeader, VExpansionPanelContent,
    VFileInput,
    VFooter,
    VForm,
    VContainer, VCol, VRow, VSpacer, VLayout, VFlex,
    VHover,
    VIcon,
    VImg,
    VInput,
    VItem, VItemGroup,
    VLabel,
    VLazy,
    VList, VListGroup, VListItem, VListItemAction, VListItemActionText, VListItemAvatar, VListItemContent, VListItemGroup, VListItemIcon, VListItemSubtitle, VListItemTitle,
    VMenu,
    VMessages,
    VNavigationDrawer,
    VOverflowBtn,
    VOverlay,
    VPagination,
    VSheet,
    VParallax,
    VPicker,
    VProgressCircular,
    VProgressLinear,
    VRadioGroup, VRadio,
    VRangeSlider,
    VRating,
    VResponsive,
    VSelect,
    VSkeletonLoader,
    VSlider,
    VSlideGroup, VSlideItem,
    VSnackbar,
    VSparkline,
    VSpeedDial,
    VStepper, VStepperContent, VStepperStep, VStepperHeader, VStepperItems,
    VSubheader,
    VSwitch,
    VSystemBar,
    VTabs, VTab, VTabsItems, VTabItem, VTabsSlider,
    VTextarea,
    VTextField,
    VTimeline, VTimelineItem,
    VTimePicker, VTimePickerClock, VTimePickerTitle,
    VToolbar, VToolbarItems, VToolbarTitle,
    VTooltip,
    VTreeview, VTreeviewNode,
    VWindow, VWindowItem,
    // transitions,
} from 'vuetify/lib'
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify, {
    components: {
        VApp, VAppBar, VAppBarNavIcon,
        VAlert,
        VAutocomplete,
        VAvatar,
        VBadge,
        VBanner,
        VBottomNavigation,
        VBottomSheet,
        VBreadcrumbs, VBreadcrumbsItem,
        VBtn,
        VBtnToggle,
        VCalendar, VCalendarDaily, VCalendarWeekly, VCalendarMonthly,
        VCard, VCardActions, VCardSubtitle, VCardText, VCardTitle,
        VCarousel, VCarouselItem,
        VCheckbox, VSimpleCheckbox,
        VChip,
        VChipGroup,
        VColorPicker, VColorPickerSwatches, VColorPickerCanvas,
        VContent,
        VCombobox,
        VCounter,
        VDataTable, VDataTableHeader, VEditDialog, VTableOverflow, VSimpleTable, VVirtualTable,
        VDataIterator, VDataFooter,
        VDatePicker, VDatePickerTitle, VDatePickerHeader, VDatePickerDateTable, VDatePickerMonthTable, VDatePickerYears,
        VDialog,
        VDivider,
        VExpansionPanels, VExpansionPanel, VExpansionPanelHeader, VExpansionPanelContent,
        VFileInput,
        VFooter,
        VForm,
        VContainer, VCol, VRow, VSpacer, VLayout, VFlex,
        VHover,
        VIcon,
        VImg,
        VInput,
        VItem, VItemGroup,
        VLabel,
        VLazy,
        VList, VListGroup, VListItem, VListItemAction, VListItemActionText, VListItemAvatar, VListItemContent, VListItemGroup, VListItemIcon, VListItemSubtitle, VListItemTitle,
        VMenu,
        VMessages,
        VNavigationDrawer,
        VOverflowBtn,
        VOverlay,
        VPagination,
        VSheet,
        VParallax,
        VPicker,
        VProgressCircular,
        VProgressLinear,
        VRadioGroup, VRadio,
        VRangeSlider,
        VRating,
        VResponsive,
        VSelect,
        VSkeletonLoader,
        VSlider,
        VSlideGroup, VSlideItem,
        VSnackbar,
        VSparkline,
        VSpeedDial,
        VStepper, VStepperContent, VStepperStep, VStepperHeader, VStepperItems,
        VSubheader,
        VSwitch,
        VSystemBar,
        VTabs, VTab, VTabsItems, VTabItem, VTabsSlider,
        VTextarea,
        VTextField,
        VTimeline, VTimelineItem,
        VTimePicker, VTimePickerClock, VTimePickerTitle,
        VToolbar, VToolbarItems, VToolbarTitle,
        VTooltip,
        VTreeview, VTreeviewNode,
        VWindow, VWindowItem,
        // transitions
    },
})

const opts = {
    theme: {
        themes: {
            light: {
                primary: colors.lightBlue.lighten3, //card color
                secondary: colors.grey.darken3, //common color
                accent: colors.deepPurple.accent4, //active button color
                error: colors.black, //not used color
                warning: colors.deepPurple.darken3, //process line color
                info: colors.teal.lighten2, //overlay color
                success: colors.purple.darken3, //not used color
                background: colors.grey.lighten2,
            },
            dark: {
                primary: colors.red.lighten1,
                secondary: colors.black,
                accent: colors.deepPurple.accent3,
                error: colors.white,
                warning: colors.indigo.darken4,
                info: colors.grey.darken4,
                success: colors.green.accent4,
                background: colors.grey.darken3,
            },
        },
    },
}

export default new Vuetify(opts)