import Vue from 'vue'
import {opts} from "./vuetifyOptions";
import Vuetify, {
    VAlert,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAutocomplete,
    VAvatar,
    VBadge,
    VBanner,
    VBottomNavigation,
    VBottomSheet,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VBtn,
    VBtnToggle,
    VCalendar,
    VCalendarDaily,
    VCalendarMonthly,
    VCalendarWeekly,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCarousel,
    VCarouselItem,
    VCheckbox,
    VChip,
    VChipGroup,
    VCol,
    VColorPicker,
    VColorPickerCanvas,
    VColorPickerSwatches,
    VCombobox,
    VContainer,
    VContent,
    VCounter,
    VDataFooter,
    VDataIterator,
    VDataTable,
    VDataTableHeader,
    VDatePicker,
    VDatePickerDateTable,
    VDatePickerHeader,
    VDatePickerMonthTable,
    VDatePickerTitle,
    VDatePickerYears,
    VDialog,
    VDivider,
    VEditDialog,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VExpansionPanels,
    VFileInput,
    VFlex,
    VFooter,
    VForm,
    VHover,
    VIcon,
    VImg,
    VInput,
    VItem,
    VItemGroup,
    VLabel,
    VLayout,
    VLazy,
    VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemActionText,
    VListItemAvatar,
    VListItemContent,
    VListItemGroup,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VMenu,
    VMessages,
    VNavigationDrawer,
    VOverflowBtn,
    VOverlay,
    VPagination,
    VParallax,
    VPicker,
    VProgressCircular,
    VProgressLinear,
    VRadio,
    VRadioGroup,
    VRangeSlider,
    VRating,
    VResponsive,
    VRow,
    VSelect,
    VSheet,
    VSimpleCheckbox,
    VSimpleTable,
    VSkeletonLoader,
    VSlideGroup,
    VSlideItem,
    VSlider,
    VSnackbar,
    VSpacer,
    VSparkline,
    VSpeedDial,
    VStepper,
    VStepperContent,
    VStepperHeader,
    VStepperItems,
    VStepperStep,
    VSubheader,
    VSwitch,
    VSystemBar,
    VTab,
    VTabItem,
    VTableOverflow,
    VTabs,
    VTabsItems,
    VTabsSlider,
    VTextarea,
    VTextField,
    VTimeline,
    VTimelineItem,
    VTimePicker,
    VTimePickerClock,
    VTimePickerTitle,
    VToolbar,
    VToolbarItems,
    VToolbarTitle,
    VTooltip,
    VTreeview,
    VTreeviewNode,
    VVirtualTable,
    VWindow,
    VWindowItem,
} from 'vuetify/lib'

import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify, {
    components: {
        VApp, VAppBar, VAppBarNavIcon,
        VAlert,
        VAutocomplete,
        VAvatar,
        VBadge,
        VBanner,
        VBottomNavigation,
        VBottomSheet,
        VBreadcrumbs, VBreadcrumbsItem,
        VBtn,
        VBtnToggle,
        VCalendar, VCalendarDaily, VCalendarWeekly, VCalendarMonthly,
        VCard, VCardActions, VCardSubtitle, VCardText, VCardTitle,
        VCarousel, VCarouselItem,
        VCheckbox, VSimpleCheckbox,
        VChip,
        VChipGroup,
        VColorPicker, VColorPickerSwatches, VColorPickerCanvas,
        VContent,
        VCombobox,
        VCounter,
        VDataTable, VDataTableHeader, VEditDialog, VTableOverflow, VSimpleTable, VVirtualTable,
        VDataIterator, VDataFooter,
        VDatePicker, VDatePickerTitle, VDatePickerHeader, VDatePickerDateTable, VDatePickerMonthTable, VDatePickerYears,
        VDialog,
        VDivider,
        VExpansionPanels, VExpansionPanel, VExpansionPanelHeader, VExpansionPanelContent,
        VFileInput,
        VFooter,
        VForm,
        VContainer, VCol, VRow, VSpacer, VLayout, VFlex,
        VHover,
        VIcon,
        VImg,
        VInput,
        VItem, VItemGroup,
        VLabel,
        VLazy,
        VList, VListGroup, VListItem, VListItemAction, VListItemActionText, VListItemAvatar, VListItemContent, VListItemGroup, VListItemIcon, VListItemSubtitle, VListItemTitle,
        VMenu,
        VMessages,
        VNavigationDrawer,
        VOverflowBtn,
        VOverlay,
        VPagination,
        VSheet,
        VParallax,
        VPicker,
        VProgressCircular,
        VProgressLinear,
        VRadioGroup, VRadio,
        VRangeSlider,
        VRating,
        VResponsive,
        VSelect,
        VSkeletonLoader,
        VSlider,
        VSlideGroup, VSlideItem,
        VSnackbar,
        VSparkline,
        VSpeedDial,
        VStepper, VStepperContent, VStepperStep, VStepperHeader, VStepperItems,
        VSubheader,
        VSwitch,
        VSystemBar,
        VTabs, VTab, VTabsItems, VTabItem, VTabsSlider,
        VTextarea,
        VTextField,
        VTimeline, VTimelineItem,
        VTimePicker, VTimePickerClock, VTimePickerTitle,
        VToolbar, VToolbarItems, VToolbarTitle,
        VTooltip,
        VTreeview, VTreeviewNode,
        VWindow, VWindowItem,
        // transitions
    },
})

export default new Vuetify(opts)